server.host: "127.0.0.3"
server.port: 8083
server.verbose: False

encoder.pca: True
encoder.pca_path: "C:\\Users\\david\\Documents\\Workspace\\pca\\model.joblib"
encoder.config_path: C:\\Users\\david\\git\\microbat\\microbat\\Python_Server\\Models\\configs\\encoder_config.yaml
encoder.encoder_path: "C:\\Users\\david\\Documents\\Workspace\\encoder_80_20230629\\epoch_latest.pt"
encoder.work_embedding_path: "C:\\Users\\david\\Documents\\fasttext\\wiki.en.bin"

data.input_size: 2
data.hidden_sizes: [4]
data.output_size: 3
data.capacity: 10000

training.epochs: 1000
training.batch_size: 64
training.gamma: 0.99
training.eps_start: 0.9
training.eps_end: 0.05
training.eps_decay: 1000
training.lr: 1.0e-4
training.tau: 0.005
training.device: cuda
training.feedback_sim: 0.8
training.var_type_sim: 0.8
training.var_name_sim: 0.8
training.reward_weight: 0.8

training.save_interval: 10
training.output_path: C:\\Users\\david\\Documents\\Workspace\\BackwardTrainer
training.load_model: True
training.load_path: "C:\\Users\\david\\Documents\\Workspace\\BackwardTrainer\\epoch_260.pt"