data.train_data_path: E:\david\FeatureDataset\data_labeled.json 
data.eval_data_path: E:\david\FeatureDataset\val.json

# data.train_data_path: E:\david\TestDataset
data.batch_size: 512
data.num_workers: 10
data.input_size: 509
data.hidden_sizes: [256, 128]
data.output_size: 64

training.device: "cuda"
training.num_epoch: 20
training.lr: 0.01

training.save_interval: 5
training.output_path: C:\Users\david\Documents\Workspace
training.version: encoder_80_20230630

visualization.log_interval: 10
visualization.sample_size: 100

eval.model_path: C:\Users\david\Documents\Workspace\encoder_20230524\epoch_5.pt